spring:
    liquibase:
        enabled: true
        url: jdbc:postgresql://localhost:5433/mediaspace
        password: pass
        user: postgres
        driver-class-name: org.postgresql.Driver
        change-log: /db/changelog/db.changelog-master.yaml
    application:
        name: mediaspace
    datasource:
        url: jdbc:postgresql://localhost:5433/mediaspace
        username: postgres
        password: pass
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none  # to not have any conflict with Liquibase
        show-sql: true

logging:
    level:
        org.springframework: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: TRACE
        org.springframework.validation: DEBUG
        org.hibernate.validator: DEBUG

